name: docker ci test

on:
  # 推送事件
  push:
    branches:
      - test


env:
  ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  DOCKERHUB_REGISTRY: docker.io
  
  
jobs:
  docker-image-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Echo Available platforms
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      
      # see: https://docs.github.com/en/actions/learn-github-actions/environment-variables
      - name: Print Github Environment Variables
        run: |
          echo "RepositoryName:      ${{ github.event.repository.name }}"
          echo "Ref:      ${{ github.ref }}"
          echo "Ref:      ${{ ALIYUN_REGISTRY }}"
      
      - name: Get Metadata (Tags、Labels)
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ ALIYUN_REGISTRY }}/jiangore/sentinel-dashboard
            ${{ DOCKERHUB_REGISTRY }}/jiangore/sentinel-dashboard
          # type的9种类型
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=pep440,pattern={{version}}
            type=match,pattern=\d.\d.\d
            type=edge,branch=main
            type=ref,event=tag
            type=raw,value=latest
            type=raw,value=main
            type=sha
          labels: |
            org.opencontainers.image.author=jiangore
            
      
