name: Push Image To Dockerhub & Aliyun Registry

on:
  # 推送事件
  push:
    branches:
      - main
    tags:
      # 触发v开头的TAG 'v*' 'v*.*.*'
      - 'v*'
  # 合并请求事件
  pull_request:
    branches:
      - 'main'
      
env:
  ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  DOCKERHUB_REGISTRY: docker.io
  
  
jobs:
  push_docker_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
    
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Get Metadata (Tags、Labels)
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.ALIYUN_REGISTRY }}/jiangore/sentinel-dashboard
            ${{ env.DOCKERHUB_REGISTRY }}/jiangore/sentinel-dashboard
          tags: |
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.author=jiangore
            
      - name: Login Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Login Aliyun Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          
      - name: Build And Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
